package Euler;

//Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//
//Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
//Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
//Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
//It can be verified that T_285 = P_165 = H_143 = 40755.
//
//Find the next triangle number that is also pentagonal and hexagonal.

public class EulerP45 {
	
	public static void main(String[] args){
		long startTime		= System.currentTimeMillis();
		 
		EulerP45 problem	= new EulerP45();
		problem.solve();
		
		System.out.println("\nElapsed time: "+ (System.currentTimeMillis() - startTime) +" ms");	
		
	}
	
	
	public void solve(){
		
	}

}
