package eulerComplete;

//Each new term in the Fibonacci sequence is generated by adding the previous two 
//terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed 
//four million, find the sum of the even-valued terms.

public class EulerP2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		long startTime	= System.currentTimeMillis();
		
		EulerP2 problem	= new EulerP2();
		problem.solve(4000000);
		
		System.out.println("Elapsed time: " + (System.currentTimeMillis() - startTime) + " ms");
		
	}
	
	public void solve(int limit){
		int i 			= 0;
		int prev		= 2;
		int prev_prev	= 1;
		int sum 		= prev;
		
		while( i < limit ){
			i 			= prev + prev_prev;			
			prev_prev	= prev;
			prev		= i;
			
			if( (i % 2) == 0){
				sum += i;
				System.out.println("Found an even-valued Fibonacci-number! : " + i);
			}			
		}
		
		System.out.println("================");
		System.out.println("Sum of even-valued fibonaci-numbers below " + limit + " :" + sum);

	}
}